error_reporting=E_ALL
display_errors=On
display_startup_errors=On
;extension=intl.so
;intl.default_locale=
default_charset="UTF-8"
auto_detect_line_endings=On

xdebug.mode=coverage
xdebug.client_host=host.docker.internal
xdebug.client_port=9003

; Полностью отключаем OpCache для разработки
opcache.enable=0
opcache.enable_cli=0

; Отключаем JIT компиляцию
opcache.jit=0
opcache.jit_buffer_size=0

; Быстрая проверка изменений файлов
opcache.validate_timestamps=1
opcache.revalidate_freq=0

; Отключаем кеширование в памяти
opcache.memory_consumption=0
opcache.interned_strings_buffer=0
opcache.max_accelerated_files=0